### ISSUE TITLE
совместимость с civil 3D 2021

### ISSUE THREAD

**Issue by r00teniy** [triroakenshield/RosReestrImpLib#1]
здравствуйте, при попытке импортировать xml в 2021 версии получается критическая ошибка, возможно дело в том, что я использовал релиз 2018 года, если есть возможность не могули бы вы скомпилировать текущую версию и сделать более новый релиз. Заранее спасибо

**Comment by triroakenshield** [comment]
попробуй эту версию - https://geodesist.ru/resources/konverter-iz-rosreestrovskogo-xml-v-tab-mif-csv.236/updates
извини, что так поздно

**Comment by r00teniy** [comment]
ничего страшного, эта версия крешей не вызывает, но и ничего не создаёт. но тут я думаю могут быть проблемы с моими XMLями, т.к. они стары, попробую найти поновее завтра. Если есть возможность посмотрите построит ли он из этого. У меня от просто даже RRViewer1ом не открывается нормально, так что я думаю дело в XMLе
[7.zip](https://github.com/triroakenshield/RosReestrImpLib/files/5241133/7.zip)

**Comment by triroakenshield** [comment]
прога может открывать любые файлы росреестра, но их надо прописать в rule.xml, например так https://geodesist.ru/threads/konverter-iz-rosreestrovskogo-xml-v-tab-mif-csv.73789/page-3#post-846884
описание структуры rule.xml - https://geodesist.ru/threads/konverter-iz-rosreestrovskogo-xml-v-tab-mif-csv.73789/#post-843096

**Comment by r00teniy** [comment]
Спасибо, буду изучать.
